# Generated by Django 5.1.6 on 2025-02-27 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingmodel',
            name='customer_user',
            field=models.ForeignKey(blank=True, help_text='If Customer already have an account. Then select customer.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_management_app.customermodel'),
        ),
    ]
