# Generated by Django 5.1.6 on 2025-02-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='employee_address',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
