# Generated by Django 5.1.6 on 2025-02-28 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_app', '0002_alter_billingmodel_customer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SidebarAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='employee_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='sidebar_access',
            field=models.ManyToManyField(blank=True, to='inventory_management_app.sidebaraccess'),
        ),
    ]
