# Generated by Django 5.1.6 on 2025-02-23 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_app', '0002_alter_employeemodel_employee_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='customer_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='employee_address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
