# Generated by Django 5.1.6 on 2025-02-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_app', '0003_sidebaraccess_alter_employeemodel_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemodel',
            name='sidebar_access',
        ),
        migrations.DeleteModel(
            name='SidebarAccess',
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='sidebar_access',
            field=models.TextField(blank=True, null=True),
        ),
    ]
