# Generated by Django 5.1.6 on 2025-02-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_app', '0003_alter_customermodel_customer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinemodel',
            name='medicine_type',
            field=models.CharField(choices=[('Liquids', 'Lliquids'), ('Solids', 'Solids')], help_text='Select Medicine Type', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderitemmodel',
            name='medicine_quantity',
            field=models.IntegerField(default=0, help_text='Add the Medicine quantity into ml/gm', null=True),
        ),
    ]
