# Generated by Django 5.1.6 on 2025-02-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_app', '0004_alter_medicinemodel_medicine_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinemodel',
            name='pack_unit',
            field=models.CharField(choices=[('ml', 'ml'), ('gm', 'gm'), ('x', 'x')], max_length=10, null=True),
        ),
    ]
