# Generated by Django 5.1.6 on 2025-02-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_app', '0004_remove_employeemodel_sidebar_access_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemodel',
            name='sidebar_access',
        ),
        migrations.AddField(
            model_name='inventoryuser',
            name='user_access_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
