# Generated by Django 5.1.6 on 2025-02-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_app', '0005_remove_employeemodel_sidebar_access_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryuser',
            name='user_access_list',
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='user_access_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
