# Generated by Django 5.1.6 on 2025-02-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_app', '0005_medicinemodel_pack_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinemodel',
            name='pack_size',
            field=models.PositiveIntegerField(default=0, help_text='Pack size unit must be the ml/gm/x.', null=True),
        ),
    ]
