# Generated by Django 5.1.6 on 2025-02-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_app', '0006_alter_medicinemodel_pack_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinemodel',
            name='medicine_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicinemodel',
            name='medicine_type',
            field=models.CharField(choices=[('Liquids', 'Lliquids'), ('Solids', 'Solids')], max_length=10, null=True),
        ),
    ]
