# Generated by Django 5.1.6 on 2025-03-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_app', '0007_remove_employeemodel_user_access_list_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingmodel',
            old_name='discount',
            new_name='discount_amount',
        ),
        migrations.RenameField(
            model_name='billingmodel',
            old_name='tax',
            new_name='discount_percentage',
        ),
        migrations.AddField(
            model_name='billingmodel',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='billingmodel',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='medicinemodel',
            name='medicine_type',
            field=models.CharField(choices=[('Liquids', 'Liquids'), ('Solids', 'Solids')], max_length=10, null=True),
        ),
    ]
