# Generated by Django 5.1.6 on 2025-02-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_app', '0007_alter_medicinemodel_medicine_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Inventory Manager', 'Inventory Manager'), ('Billing Staff', 'Billing Staff')], max_length=20, null=True),
        ),
    ]
