# Generated by Django 5.1.6 on 2025-03-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_app', '0008_rename_discount_billingmodel_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingmodel',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Mention the no of percentage discount.', max_digits=6, null=True),
        ),
    ]
