# Generated by Django 5.1.6 on 2025-02-26 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_app', '0008_alter_inventoryuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineUnitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='medicinemodel',
            name='pack_units',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine_unit', to='inventory_management_app.medicineunitmodel'),
        ),
    ]
