# Generated by Django 5.1.6 on 2025-03-05 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_app', '0009_alter_billingmodel_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingmodel',
            name='customer_user',
            field=models.ForeignKey(blank=True, help_text='If Customer already has an account, select the customer.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_management_app.customermodel'),
        ),
        migrations.AlterField(
            model_name='billingmodel',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Mention the number of percentage discount.', max_digits=6, null=True),
        ),
    ]
