# Generated by Django 5.1.6 on 2025-02-26 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_app', '0009_medicineunitmodel_medicinemodel_pack_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinemodel',
            name='pack_unit',
        ),
    ]
