# Generated by Django 5.1.6 on 2025-02-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_app', '0010_remove_medicinemodel_pack_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinemodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
