# Generated by Django 5.1.6 on 2025-03-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_app', '0011_billingmodel_calculation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingitemmodel',
            name='calculation_type',
            field=models.CharField(blank=True, choices=[('Pack', 'Pack'), ('Unit', 'Unit')], default='Unit', max_length=10, null=True),
        ),
    ]
