# Generated by Django 5.1.6 on 2025-02-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_app', '0011_alter_medicinemodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinemodel',
            name='sku',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
