# Generated by Django 5.1.6 on 2025-02-27 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_app', '0012_medicinemodel_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
