# Generated by Django 5.1.6 on 2025-03-05 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_app', '0012_billingitemmodel_calculation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingmodel',
            name='calculation_type',
        ),
    ]
