# Generated by Django 5.1.6 on 2025-02-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_app', '0013_ordermodel_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinemodel',
            name='stocks',
            field=models.CharField(choices=[('Available', 'Available'), ('Out of Stock', 'Out of Stock')], default='Out of Stock', max_length=20, null=True),
        ),
    ]
