# Generated by Django 5.1.6 on 2025-03-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_app', '0013_remove_billingmodel_calculation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinemodel',
            name='total_medicine',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
