# Generated by Django 5.1.6 on 2025-03-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_app', '0014_medicinemodel_total_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinemodel',
            name='total_medicine',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
