# Generated by Django 5.1.6 on 2025-03-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_app', '0015_alter_medicinemodel_total_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingitemmodel',
            name='medicine_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
