# Generated by Django 5.1.6 on 2025-03-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_app', '0017_alter_medicinemodel_total_case_pack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingmodel',
            name='customer_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='billingmodel',
            name='customer_dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
