# Generated by Django 5.1.6 on 2025-03-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_app', '0020_alter_billingitemmodel_medicine_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinemodel',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, help_text='Unit price of the product calculated by per per pack size. This is the sale price', max_digits=10, null=True),
        ),
    ]
