# Generated by Django 5.1.6 on 2025-03-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_app', '0021_alter_medicinemodel_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottlebreakagemodel',
            name='lost_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Add the lost quantity as unit: e.g.,ml/gm', max_digits=10, null=True),
        ),
    ]
