# Generated by Django 5.1.6 on 2025-03-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_app', '0023_alter_bottlebreakagemodel_lost_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinemodel',
            name='brand_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='billingmodel',
            name='billing_status',
            field=models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Google Pay', 'Google Pay'), ('PhonePe', 'PhonePe'), ('Debit Card', 'Debit Card'), ('Credit Card', 'Credit Card'), ('Due', 'Due')], default='Progress', max_length=20, null=True),
        ),
    ]
