# Generated by Django 5.1.6 on 2025-03-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_app', '0027_alter_billingmodel_customer_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingmodel',
            name='customer_dob',
            field=models.CharField(blank=True, help_text='Format: DD-MM', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='customer_dob',
            field=models.CharField(blank=True, help_text='Format: DD-MM', max_length=5, null=True),
        ),
    ]
