# Generated by Django 5.1.6 on 2025-04-16 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_app', '0028_alter_billingmodel_customer_dob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinemodel',
            name='expire_date',
        ),
        migrations.RemoveField(
            model_name='medicinemodel',
            name='manufacturing_date',
        ),
    ]
