# Generated by Django 5.1.6 on 2025-04-19 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_app', '0029_remove_medicinemodel_expire_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingitemmodel',
            old_name='unit_price',
            new_name='unit_sale_price',
        ),
        migrations.RenameField(
            model_name='medicinemodel',
            old_name='unit_price',
            new_name='unit_sale_price',
        ),
    ]
