# Generated by Django 5.1.6 on 2025-04-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_app', '0030_rename_unit_price_billingitemmodel_unit_sale_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinemodel',
            name='unit_sale_price',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, help_text='Unit sale price of the product calculated by per pack size. This is the sale price', max_digits=10, null=True),
        ),
    ]
