# Generated by Django 5.1.6 on 2025-04-19 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_app', '0031_alter_medicinemodel_unit_sale_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicinemodel',
            old_name='total_case_pack',
            new_name='total_quantity',
        ),
        migrations.RenameField(
            model_name='medicinestockmodel',
            old_name='total_case_pack',
            new_name='total_quantity',
        ),
    ]
