# Generated by Django 5.1.6 on 2025-04-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_app', '0032_rename_total_case_pack_medicinemodel_total_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinemodel',
            name='gst',
            field=models.CharField(blank=True, choices=[('5%', '5%'), ('12%', '12%'), ('18%', '18%'), ('28%', '28%')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='medicinemodel',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
