# Generated by Django 5.1.6 on 2025-04-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_app', '0033_medicinemodel_gst_medicinemodel_gst_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingmodel',
            old_name='tax_amount',
            new_name='total_tax_amount',
        ),
        migrations.RemoveField(
            model_name='billingmodel',
            name='tax_percentage',
        ),
        migrations.RemoveField(
            model_name='medicinemodel',
            name='gst',
        ),
        migrations.AddField(
            model_name='billingitemmodel',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='billingitemmodel',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='medicinemodel',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='medicinemodel',
            name='gst_percentage',
            field=models.CharField(blank=True, choices=[('5%', '5%'), ('12%', '12%'), ('18%', '18%'), ('28%', '28%')], max_length=10, null=True),
        ),
    ]
