# Generated by Django 5.1.6 on 2025-04-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_app', '0034_rename_tax_amount_billingmodel_total_tax_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingitemmodel',
            name='gst_percentage',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
