# Generated by Django 5.1.6 on 2025-04-20 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_app', '0035_alter_billingitemmodel_gst_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingmodel',
            name='total_tax_amount',
        ),
    ]
