# Generated by Django 5.1.6 on 2025-05-07 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_app', '0036_remove_billingmodel_total_tax_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinemodel',
            name='slug',
        ),
    ]
