# Generated by Django 5.1.6 on 2025-05-08 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_app', '0037_remove_medicinemodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinemodel',
            name='sku',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='medicinemodel',
            index=models.Index(fields=['-total_medicine'], name='inventory_m_total_m_587eb5_idx'),
        ),
    ]
