# Generated by Django 5.1.6 on 2025-05-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_app', '0038_alter_medicinemodel_sku_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SKUCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_sku_number', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
