# Generated by Django 5.1.6 on 2025-05-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_app', '0039_skucounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinemodel',
            name='medicine_type',
            field=models.CharField(choices=[('LIQUID', 'LIQUID'), ('SOLID', 'SOLID')], max_length=10, null=True),
        ),
    ]
